version: '3.7'

services:
  example-app:
    image: example:latest
    environment:
      SOME_VAR: ${APPNAME_VAR_NAME:-}
    labels:
      # ...
    ports:
      # ...
    volumes:
      # ...
    profiles:
      - appname
      - appname-setup

volumes:
  # ... Add any volumes that should not be backed by app_data

