{
 "title": "Node Temperature Details",
 "tags": [
  "Percona",
  "OS"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "node_name",
    "label": "Node Name",
    "query": {
     "query": "label_values(node_hwmon_chip_names, node_name)"
    }
   },
   {
    "name": "service",
    "label": "Service Name",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, service_name)"
    }
   },
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, environment)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, cluster)"
    }
   },
   {
    "name": "replication_set",
    "label": "Replication Set",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, replication_set)"
    }
   },
   {
    "name": "db",
    "label": "Database",
    "query": {
     "query": "label_values(pg_stat_database_tup_fetched{service_name=~\"$service\",datname!~\"template.*|postgres\"},datname)"
    }
   },
   {
    "name": "node_type",
    "label": "Type",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, node_type)"
    }
   },
   {
    "name": "service_type",
    "label": "Type",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, service_type)"
    }
   },
   {
    "name": "username",
    "label": "Username",
    "query": {
     "query": "label_values(mysql_info_schema_user_statistics_connected_time_seconds_total{service_name=\"$service_name\"},user)"
    }
   },
   {
    "name": "schema",
    "label": "Schema",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, schema)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "description": "Expose hardware monitoring and sensor data from `/sys/class/hwmon/`",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<h1 style='color:#5991A7;font-weight:bold;text-align:center;font-style:italic'>Data for <span style='color:#e68a00'>$node_name</span> with <span style='color:#e68a00'>$interval</span> resolution</h1>"
   }
  },
  {
   "title": "CPU Cores Temperatures",
   "type": "graph",
   "description": "Data is taken from temperature sensors that are connected to CPUs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "(sum by (sensor,node_name,chip) (node_hwmon_temp_celsius{node_name=~\"$node_name\"})) * on(sensor) group_left(label) (sum by (sensor,label,node_name) (node_hwmon_sensor_label{node_name=~\"$node_name\",label=~\"core.*\"}))",
     "legendFormat": "{{chip}} - {{label}}"
    }
   ]
  },
  {
   "title": "Chips Temperatures",
   "type": "graph",
   "description": "Hardware monitoring devices let you monitor the hardware health of a system. Most modern motherboards include such a device. It can include temperature sensors, voltage sensors, fan speed sensors and various additional features such as the ability to control the speed of the fans. \n\nIf the temperature is 511C, it means that reading of a chip sensor has failed. Please consider installing/updating a driver and check if the sensors are properly configured.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (chip, node_name) (node_hwmon_temp_celsius{node_name=~\"$node_name\"})",
     "legendFormat": "{{chip}}"
    }
   ]
  },
  {
   "title": "Fan Rotation Speeds",
   "type": "graph",
   "description": "Fan rotation speeds are reported in RPM (rotations per minute).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "rpm" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "max_over_time(node_hwmon_fan_rpm{node_name=\"$node_name\"}[$interval]) or max_over_time(node_hwmon_fan_rpm{node_name=\"$node_name\"}[5m])",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": " Fan Power Usage",
   "type": "graph",
   "description": "Pulse width modulation fan control. PWM operates like a switch which constantly cycles on and off, thereby regulating the amount of power the fan or pump motor gains.  255 is max or 100%.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "(max_over_time(node_hwmon_pwm{node_name=~\"$node_name\"}[$interval]) or max_over_time(node_hwmon_pwm{node_name=~\"$node_name\"}[5m]))/255",
     "legendFormat": "{{sensor}}"
    }
   ]
  }
 ]
}