{
 "title": "PostgreSQL Instance Summary",
 "tags": [
  "Percona",
  "PostgreSQL"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "work_mem",
    "query": {
     "query": "query_result(pg_settings_work_mem_bytes{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "node_name",
    "label": "Node Name",
    "query": {
     "query": "label_values(pg_up{service_name=~\"$service_name\"},node_name)"
    }
   },
   {
    "name": "crop_host",
    "label": "Node Name",
    "query": {
     "query": "label_values(pg_up{node_name=~\"$node_name\"},node_name)"
    }
   },
   {
    "name": "service_name",
    "label": "Service Name",
    "query": {
     "query": "label_values(pg_up, service_name)"
    }
   },
   {
    "name": "database",
    "label": "DB",
    "query": {
     "query": "label_values(pg_stat_database_tup_fetched{service_name=~\"$service_name\",datname!~\"template.*|postgres\"},datname)"
    }
   },
   {
    "name": "version",
    "query": {
     "query": "label_values(pg_static{service_name=~\"$service_name\"},version)"
    }
   },
   {
    "name": "max_connections",
    "query": {
     "query": "query_result(pg_settings_max_connections{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "shared_buffers",
    "query": {
     "query": "query_result(pg_settings_shared_buffers_bytes{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "wal_buffers",
    "query": {
     "query": "query_result(pg_settings_wal_buffers_bytes{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "wal_segment_size",
    "query": {
     "query": "query_result(pg_settings_wal_segment_size_bytes{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "maintenance_work_mem",
    "query": {
     "query": "query_result(pg_settings_maintenance_work_mem_bytes{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "block_size",
    "query": {
     "query": "query_result(pg_settings_block_size{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "checkpoint_segments",
    "query": {
     "query": "query_result(pg_settings_checkpoint_segments{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "checkpoint_timeout",
    "query": {
     "query": "query_result(pg_settings_checkpoint_timeout_seconds{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "fsync",
    "query": {
     "query": "query_result(pg_settings_fsync{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "default_statistics_target",
    "query": {
     "query": "query_result(pg_settings_default_statistics_target{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "seq_page_cost",
    "query": {
     "query": "query_result(pg_settings_seq_page_cost{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "random_page_cost",
    "query": {
     "query": "query_result(pg_settings_random_page_cost{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "effective_cache_size",
    "query": {
     "query": "query_result(pg_settings_effective_cache_size_bytes{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "effective_io_concurrency",
    "query": {
     "query": "query_result(pg_settings_effective_io_concurrency{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "autovacuum",
    "query": {
     "query": "query_result(pg_settings_autovacuum{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "autovacuum_analyze_scale_factor",
    "query": {
     "query": "query_result(pg_settings_autovacuum_analyze_scale_factor{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "autovacuum_analyze_threshold",
    "query": {
     "query": "query_result(pg_settings_autovacuum_analyze_threshold{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "autovacuum_vacuum_scale_factor",
    "query": {
     "query": "query_result(pg_settings_autovacuum_vacuum_scale_factor{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "autovacuum_vacuum_threshold",
    "query": {
     "query": "query_result(pg_settings_autovacuum_vacuum_threshold{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "autovacuum_vacuum_cost_limit",
    "query": {
     "query": "query_result(pg_settings_autovacuum_vacuum_cost_limit{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "autovacuum_vacuum_cost_delay",
    "query": {
     "query": "query_result(pg_settings_autovacuum_vacuum_cost_delay_seconds{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "autovacuum_max_workers",
    "query": {
     "query": "query_result(pg_settings_autovacuum_max_workers{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "autovacuum_naptime",
    "query": {
     "query": "query_result(pg_settings_autovacuum_naptime_seconds{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "autovacuum_freeze_max_age",
    "query": {
     "query": "query_result(pg_settings_autovacuum_freeze_max_age{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "logging_collector",
    "query": {
     "query": "query_result(pg_settings_logging_collector{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "log_min_duration_statement",
    "query": {
     "query": "query_result(pg_settings_log_min_duration_statement_seconds{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "log_duration",
    "query": {
     "query": "query_result(pg_settings_log_duration{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "log_lock_waits",
    "query": {
     "query": "query_result(pg_settings_log_lock_waits{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "max_wal_senders",
    "query": {
     "query": "query_result(pg_settings_max_wal_senders{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "max_wal_size",
    "query": {
     "query": "query_result(pg_settings_max_wal_size_bytes{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "min_wal_size",
    "query": {
     "query": "query_result(pg_settings_min_wal_size_bytes{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "wal_compression",
    "query": {
     "query": "query_result(pg_settings_wal_compression{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "max_worker_processes",
    "query": {
     "query": "query_result(pg_settings_max_worker_processes{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "max_parallel_workers_per_gather",
    "query": {
     "query": "query_result(pg_settings_max_parallel_workers_per_gather{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "max_parallel_workers",
    "query": {
     "query": "query_result(pg_settings_max_parallel_workers_per_gather{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "autovacuum_work_mem",
    "query": {
     "query": "query_result(pg_settings_autovacuum_work_mem_bytes{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "autovacuum_multixact_freeze_max_age",
    "query": {
     "query": "query_result(pg_settings_autovacuum_multixact_freeze_max_age{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, environment)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, cluster)"
    }
   },
   {
    "name": "replication_set",
    "label": "Replication Set",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, replication_set)"
    }
   },
   {
    "name": "node_type",
    "label": "Type",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, node_type)"
    }
   },
   {
    "name": "service_type",
    "label": "Type",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, service_type)"
    }
   },
   {
    "name": "username",
    "label": "Username",
    "query": {
     "query": "label_values(mysql_info_schema_user_statistics_connected_time_seconds_total{service_name=\"$service_name\"},user)"
    }
   },
   {
    "name": "schema",
    "label": "Schema",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, schema)"
    }
   },
   {
    "name": "service_id",
    "label": "Service ID",
    "query": {
     "query": "label_values(pg_up{service_name=\"$service_name\"}, service_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<h1 style='color:#5991A7;font-weight:bold;text-align:center;font-style:italic'>Data for <span style='color:#e68a00'>$service_name</span> with <span style='color:#e68a00'>$interval</span> resolution</h1>"
   }
  },
  {
   "title": "Connected",
   "type": "stat",
   "description": "Reports whether PMM Server can connect to the PostgreSQL instance.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg by (service_name) (pg_up{service_name=~\"$service_name\"})"
    }
   ]
  },
  {
   "title": "Node",
   "type": "text",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 3 },
   "options": {
    "content": "<h5 style='color:#e68a00;font-weight:bold;text-align:center'><a href=\"/graph/d/node-instance-summary/node-summary?var-node_name=$node_name\" target=\"_blank\">$crop_host...</a></h5>"
   }
  },
  {
   "title": "Version",
   "type": "text",
   "description": "The version of the PostgreSQL instance.",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 3 },
   "options": {
    "content": "<h3 style='color:#e68a00;font-weight:bold;text-align:center'>$version</h3>"
   }
  },
  {
   "title": "Shared Buffers",
   "type": "stat",
   "description": "Defines the amount of memory the database server uses for shared memory buffers.  Default is 128MB.  Guidance on tuning is 25% of RAM, but generally doesn't exceed 40%.",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (service_name) (max_over_time(pg_settings_shared_buffers_bytes{service_name=~\"$service_name\"}[$interval]) or\nmax_over_time(pg_settings_shared_buffers_bytes{service_name=~\"$service_name\"}[5m])) "
    }
   ]
  },
  {
   "title": "Memory Size for each Sort",
   "type": "stat",
   "description": "The parameter work_mem defines the amount of memory assigned for internal sort operations and hash tables before writing to temporary disk files.  The default is 4MB.",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (service_name) (max_over_time(pg_settings_work_mem_bytes{service_name=~\"$service_name\"}[$interval]) or\nmax_over_time(pg_settings_work_mem_bytes{service_name=~\"$service_name\"}[5m]))"
    }
   ]
  },
  {
   "title": "Autovacuum",
   "type": "stat",
   "description": "Whether autovacuum process is enabled or not.  Generally the solution is to vacuum more often, not less.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (service_name) (max_over_time(pg_settings_autovacuum{service_name=~\"$service_name\"}[$interval]) or\nmax_over_time(pg_settings_autovacuum{service_name=~\"$service_name\"}[5m]))"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (service_name) (pg_postmaster_uptime_seconds{service_name=~\"$service_name\"})"
    }
   ]
  },
  {
   "title": "Max Connections",
   "type": "stat",
   "description": "The maximum number of client connections allowed.  Change this value with care as there are some memory resources that are allocated on a per-client basis, so setting max_connections higher will generally increase overall PostgreSQL memory usage.",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (service_name) (max_over_time(pg_settings_max_connections{service_name=~\"$service_name\"}[$interval]) or\nmax_over_time(pg_settings_max_connections{service_name=~\"$service_name\"}[5m]))"
    }
   ]
  },
  {
   "title": "Disk Cache Size",
   "type": "stat",
   "description": "PostgreSQL's effective_cache_size variable tunes how much RAM you expect to be available for disk caching.  Generally adding Linux free+cached will give you a good idea.  This value is used by the query planner whether plans will fit in memory, and when defined too low, can lead to some plans rejecting certain indexes.",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (service_name) (max_over_time(pg_settings_effective_cache_size_bytes{service_name=~\"$service_name\"}[$interval]) or\nmax_over_time(pg_settings_effective_cache_size_bytes{service_name=~\"$service_name\"}[5m]))"
    }
   ]
  },
  {
   "title": "Disk-Page Buffers",
   "type": "stat",
   "description": "The setting wal_buffers defines how much memory is used for caching the write-ahead log entries. Generally this value is small (3% of shared_buffers value), but it may need to be modified for heavily loaded servers.",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (service_name) (max_over_time(pg_settings_wal_buffers_bytes{service_name=~\"$service_name\"}[$interval]) or\nmax_over_time(pg_settings_wal_buffers_bytes{service_name=~\"$service_name\"}[5m]))"
    }
   ]
  },
  {
   "title": "Service Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Service Summary",
     "type": "pmm-pt-summary-panel",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 12 },
     "targets": [
      {}
     ]
    }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "PostgreSQL Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (service_name,state) (sum(max_over_time(pg_stat_activity_count{service_name=~\"$service_name\",datname=~\"$database\"}[$interval]) or\nmax_over_time(pg_stat_activity_count{service_name=~\"$service_name\",datname=~\"$database\"}[5m])) by (state))",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "sum(max_over_time(pg_stat_activity_count{service_name=~\"$service_name\",datname=~\"$database\"}[$interval]) or\nmax_over_time(pg_stat_activity_count{service_name=~\"$service_name\",datname=~\"$database\"}[5m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (service_name,datname) (max_over_time(pg_stat_activity_count{service_name=~\"$service_name\",datname=~\"$database\",state='active'}[$interval]) or\nmax_over_time(pg_stat_activity_count{service_name=~\"$service_name\",datname=~\"$database\",state='active'}[5m]))",
     "legendFormat": "{{datname}}"
    },
    {
     "expr": "avg by (service_name) (max_over_time(pg_settings_max_connections{service_name=~\"$service_name\"}[$interval]) or \nmax_over_time(pg_settings_max_connections{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Maximum connections"
    }
   ]
  },
  { "title": "Tuples", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Tuples",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_tup_fetched{datname=~\"$database\",instance=~\"$node_name\"}[$interval])) or \nsum(irate(pg_stat_database_tup_fetched{datname=~\"$database\",instance=~\"$node_name\"}[5m]))",
     "legendFormat": "Fetched"
    },
    {
     "expr": "sum(rate(pg_stat_database_tup_returned{datname=~\"$database\",service_name=~\"$service_name\"}[$interval])) or\nsum(irate(pg_stat_database_tup_returned{datname=~\"$database\",service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Returned"
    },
    {
     "expr": "sum(rate(pg_stat_database_tup_inserted{datname=~\"$database\",service_name=~\"$service_name\"}[$interval])) or\nsum(irate(pg_stat_database_tup_inserted{datname=~\"$database\",service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Inserted"
    },
    {
     "expr": "sum(rate(pg_stat_database_tup_updated{datname=~\"$database\",service_name=~\"$service_name\"}[$interval])) or\nsum(irate(pg_stat_database_tup_updated{datname=~\"$database\",service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Updated"
    },
    {
     "expr": "sum(rate(pg_stat_database_tup_deleted{datname=~\"$database\",service_name=~\"$service_name\"}[$interval])) or\nsum(irate(pg_stat_database_tup_deleted{datname=~\"$database\",service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Deleted"
    }
   ]
  },
  {
   "title": "Read Tuple Activity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_tup_returned{datname=~\"$database\",service_name=~\"$service_name\"}[$interval])) or\nsum(irate(pg_stat_database_tup_returned{datname=~\"$database\",service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Rows returned by queries"
    },
    {
     "expr": "sum(rate(pg_stat_database_tup_fetched{datname=~\"$database\",service_name=~\"$service_name\"}[$interval])) or\nsum(irate(pg_stat_database_tup_fetched{datname=~\"$database\",service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Rows fetched by queries"
    }
   ]
  },
  {
   "title": "Tuples Changes by Queries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_tup_inserted{datname=~\"$database\",service_name=~\"$service_name\"}[$interval])) or\nsum(irate(pg_stat_database_tup_inserted{datname=~\"$database\",service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Rows inserted by queries"
    },
    {
     "expr": "sum(rate(pg_stat_database_tup_updated{datname=~\"$database\",service_name=~\"$service_name\"}[$interval])) or\nsum(irate(pg_stat_database_tup_updated{datname=~\"$database\",service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Rows updated by queries"
    },
    {
     "expr": "sum(rate(pg_stat_database_tup_deleted{datname=~\"$database\",service_name=~\"$service_name\"}[$interval])) or\nsum(irate(pg_stat_database_tup_deleted{datname=~\"$database\",service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Rows deleted by queries"
    }
   ]
  },
  { "title": "Transactions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Transactions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_xact_commit{datname=~\"$database\",service_name=~\"$service_name\"}[$interval])) or \nsum(irate(pg_stat_database_xact_commit{datname=~\"$database\",service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Commits"
    },
    {
     "expr": "sum(rate(pg_stat_database_xact_rollback{datname=~\"$database\",service_name=~\"$service_name\"}[$interval])) or\nsum(irate(pg_stat_database_xact_rollback{datname=~\"$database\",service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Rollbacks"
    }
   ]
  },
  {
   "title": "Duration of Transactions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg by (service_name,state) (max_over_time(pg_stat_activity_max_tx_duration{service_name=~\"$service_name\"}[$interval]) or\nmax_over_time(pg_stat_activity_max_tx_duration{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "{{state}}"
    }
   ]
  },
  { "title": "Temp Files", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Number of Temp Files",
   "type": "graph",
   "description": "Cumulative number of temporary files created by queries in this database since service start. All temporary files are counted, regardless of why the temporary file was created (e.g., sorting or hashing), and regardless of the log_temp_files setting.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (service_name,datname) (max_over_time(pg_stat_database_temp_files{service_name=~\"$service_name\",datname!~\"template.*\"}[$interval]) or \nmax_over_time(pg_stat_database_temp_files{service_name=~\"$service_name\",datname!~\"template.*\"}[5m]))",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Size of Temp Files",
   "type": "graph",
   "description": "Cumulative amount of data written to temporary files by queries in this database since service start. All temporary files are counted, regardless of why the temporary file was created, and regardless of the log_temp_files setting.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg by (service_name,datname) (max_over_time(pg_stat_database_temp_bytes{service_name=~\"$service_name\",datname!~\"template.*\"}[$interval]) or \nmax_over_time(pg_stat_database_temp_bytes{service_name=~\"$service_name\",datname!~\"template.*\"}[5m]))",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Temp Files Activity",
   "type": "graph",
   "description": "Number of temporary files created by queries in this database. All temporary files are counted, regardless of why the temporary file was created (e.g., sorting or hashing), and regardless of the log_temp_files setting.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (service_name,datname) (increase(pg_stat_database_temp_files{service_name=~\"$service_name\",datname!~\"template.*\"}[$interval]))",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Temp Files Utilization",
   "type": "graph",
   "description": "Total amount of data written to temporary files by queries in this database. All temporary files are counted, regardless of why the temporary file was created, and regardless of the log_temp_files setting.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg by (service_name,datname) (increase(pg_stat_database_temp_bytes{service_name=~\"$service_name\",datname=~\"$database\",datname!~\"|template(0|1)\"}[$interval]) or \nincrease(pg_stat_database_temp_bytes{service_name=~\"$service_name\",datname=~\"$database\",datname!~\"|template(0|1)\"}[5m]))",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  { "title": "Conflicts & Locks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "Conflicts/Deadlocks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "conflicts",
     "expr": "sum(rate(pg_stat_database_deadlocks{datname=~\"$database\",service_name=~\"$service_name\"}[$interval])) or \nsum(irate(pg_stat_database_deadlocks{datname=~\"$database\",service_name=~\"$service_name\"}[5m]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Deadlocks",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "conflicts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "node_name", "operator": "=~", "value": "/^$node_name$/" }
     ]
    },
    {
     "alias": "deadlocks",
     "expr": "sum(rate(pg_stat_database_conflicts{datname=~\"$database\",service_name=~\"$service_name\"}[$interval])) or \nsum(irate(pg_stat_database_conflicts{datname=~\"$database\",service_name=~\"$service_name\"}[5m]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Conflicts",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "deadlocks" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "node_name", "operator": "=~", "value": "/^$node_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Number of Locks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "conflicts",
     "expr": "avg by (service_name,datname,mode) (max_over_time(pg_locks_count{datname=~\"$database\",service_name=~\"$service_name\",datname!~\"template.*\"}[$interval]) or\nmax_over_time(pg_locks_count{datname=~\"$database\",service_name=~\"$service_name\",datname!~\"template.*\"}[5m]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{mode}} - {{datname}}",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "conflicts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "node_name", "operator": "=~", "value": "/^$node_name$/" }
     ]
    }
   ]
  },
  { "title": "Buffers & Blocks Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "title": "Operations with Blocks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "avg by (service_name,datname) (rate(pg_stat_database_blk_read_time{datname=~\"$database\",service_name=~\"$service_name\",datname!~\"template.*|postgres\"}[$interval]) or\nirate(pg_stat_database_blk_read_time{datname=~\"$database\",service_name=~\"$service_name\",datname!~\"template.*|postgres\"}[5m]))",
     "legendFormat": "Read {{datname}}"
    },
    {
     "expr": "avg by (service_name,datname) (rate(pg_stat_database_blk_write_time{datname=~\"$database\",service_name=~\"$service_name\",datname!~\"template.*|postgres\"}[$interval]) or\nirate(pg_stat_database_blk_write_time{datname=~\"$database\",service_name=~\"$service_name\",datname!~\"template.*|postgres\"}[5m]))",
     "legendFormat": "Write {{datname}}"
    }
   ]
  },
  {
   "title": "Buffers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Buffers Allocated",
     "expr": "avg by (service_name) (rate(pg_stat_bgwriter_buffers_alloc{service_name=~\"$service_name\"}[$interval]) or \nirate(pg_stat_bgwriter_buffers_alloc{service_name=~\"$service_name\"}[5m]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Allocated",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "buffers_alloc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "node_name", "operator": "=~", "value": "/^$node_name$/" }
     ]
    },
    {
     "alias": "Buffers Allocated",
     "expr": "avg by (service_name) (rate(pg_stat_bgwriter_buffers_backend_fsync{service_name=~\"$service_name\"}[$interval]) or\nirate(pg_stat_bgwriter_buffers_backend_fsync{service_name=~\"$service_name\"}[5m]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Fsync calls by a backend",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "buffers_alloc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "node_name", "operator": "=~", "value": "/^$node_name$/" }
     ]
    },
    {
     "alias": "Buffers Allocated",
     "expr": "avg by (service_name) (rate(pg_stat_bgwriter_buffers_backend{service_name=~\"$service_name\"}[$interval]) or\nirate(pg_stat_bgwriter_buffers_backend{service_name=~\"$service_name\"}[5m]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Written directly by a backend",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "buffers_alloc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "node_name", "operator": "=~", "value": "/^$node_name$/" }
     ]
    },
    {
     "alias": "Buffers Allocated",
     "expr": "avg by (service_name) (rate(pg_stat_bgwriter_buffers_clean{service_name=~\"$service_name\"}[$interval]) or \nirate(pg_stat_bgwriter_buffers_clean{service_name=~\"$service_name\"}[5m]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Written by the background writer",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "buffers_alloc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "node_name", "operator": "=~", "value": "/^$node_name$/" }
     ]
    },
    {
     "alias": "Buffers Allocated",
     "expr": "avg by (service_name) (rate(pg_stat_bgwriter_buffers_checkpoint{service_name=~\"$service_name\"}[$interval]) or\nirate(pg_stat_bgwriter_buffers_checkpoint{service_name=~\"$service_name\"}[5m]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Written during checkpoints",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "buffers_alloc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "node_name", "operator": "=~", "value": "/^$node_name$/" }
     ]
    }
   ]
  },
  { "title": "Others", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 } },
  {
   "title": "Canceled Queries",
   "type": "graph",
   "description": "Based on pg_stat_database_conflicts view",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_conflicts_confl_bufferpin{service_name=~\"$service_name\"}[$interval])) or\nsum(irate(pg_stat_database_conflicts_confl_bufferpin{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Pinned buffers"
    },
    {
     "expr": "sum(rate(pg_stat_database_conflicts_confl_deadlock{service_name=~\"$service_name\"}[$interval])) or\nsum(irate(pg_stat_database_conflicts_confl_deadlock{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Deadlocks"
    },
    {
     "expr": "sum(rate(pg_stat_database_conflicts_confl_lock{service_name=~\"$service_name\"}[$interval])) or\nsum(irate(pg_stat_database_conflicts_confl_lock{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Lock timeouts"
    },
    {
     "expr": "sum(rate(pg_stat_database_conflicts_confl_snapshot{service_name=~\"$service_name\"}[$interval])) or\nsum(irate(pg_stat_database_conflicts_confl_snapshot{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Old snapshots"
    },
    {
     "expr": "sum(rate(pg_stat_database_conflicts_confl_tablespace{service_name=~\"$service_name\"}[$interval])) or\nsum(irate(pg_stat_database_conflicts_confl_tablespace{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Dropped tablespaces "
    }
   ]
  },
  {
   "title": "Cache Hit Ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(pg_stat_database_blks_hit{datname=~\"$database\",service_name=~\"$service_name\",datname!~\"template.*\"}) by (datname) /\n(sum(pg_stat_database_blks_hit{datname=~\"$database\",service_name=~\"$service_name\",datname!~\"template.*\"}) by (datname) + \nsum(pg_stat_database_blks_read{datname=~\"$database\",service_name=~\"$service_name\",datname!~\"template.*\"}) by (datname))",
     "legendFormat": "Cache hit rate {{datname}}"
    }
   ]
  },
  {
   "title": "Checkpoint stats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "avg by (service_name) (rate(pg_stat_bgwriter_checkpoint_sync_time{service_name=~'$service_name'}[$interval]) or\nirate(pg_stat_bgwriter_checkpoint_sync_time{service_name=~'$service_name'}[5m]))",
     "legendFormat": "Files Synchronization to disk"
    },
    {
     "expr": "avg by (service_name) (rate(pg_stat_bgwriter_checkpoint_write_time{service_name=~'$service_name'}[$interval]) or\nirate(pg_stat_bgwriter_checkpoint_write_time{service_name=~'$service_name'}[5m]))",
     "legendFormat": "Written Files to disk"
    }
   ]
  },
  {
   "title": "Settings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 97 },
   "collapsed": true,
   "panels": [
    {
     "title": "PostgreSQL Settings",
     "type": "text",
     "gridPos": { "h": 18, "w": 24, "x": 0, "y": 100 },
     "options": {
      "content": "<table style=\"width:100%; border: 2px solid grey;\">\n  <tr><td></td><td></td><td></td><td></td></tr>\n  <tr><td> The maximum number of concurrent connections </td><td>${max_connections}</td><td> Shared memory buffers (bytes) </td><td>${shared_buffers}</td></tr>\n  <tr><td> The maximum memory to be used for query workspaces (bytes)</td><td>${work_mem}</td><td> The number of disk-page buffers in shared memory for WAL (bytes)</td><td>${wal_buffers}</td></tr>\n  <tr><td> The number of pages per write ahead log segment (bytes) </td><td>${wal_segment_size}</td><td>The maximum memory to be used for query workspaces (bytes)</td><td>${maintenance_work_mem}</td></tr>\n  <tr><td> The block size in the write ahead log </td><td>${block_size}</td><td>The maximum distance in log segments between automatic WAL checkpoints</td><td>${checkpoint_segments}</td></tr>\n  <tr><td> Time spent flushing dirty buffers during checkpoint, as fraction of checkpoint interval </td><td>${checkpoint_timeout}</td><td>The maximum number of simultaneously running WAL sender processes</td><td>${max_wal_senders}</td></tr>\n  <tr><td> The minimum size to shrink the WAL to (bytes)</td><td>${min_wal_size}</td><td>The WAL size that triggers a checkpoint (bytes)</td><td>${max_wal_size}</td></tr>\n  <tr><td> Compresses full-page writes written in WAL file </td><td>${wal_compression}</td><td>Maximum number of concurrent worker processes</td><td>${max_worker_processes}</td></tr>\n  <tr><td> The maximum number of parallel processes per executor node </td><td>${max_parallel_workers_per_gather}</td><td>The maximum number of parallel processes per executor node</td><td>${max_parallel_workers}</td></tr>\n  <tr><td> The default statistics target </td><td>${default_statistics_target}</td><td>The planner's estimate of the cost of a sequentially fetched disk page </td><td>${seq_page_cost}</td></tr>\n  <tr><td> The planner's estimate of the cost of a nonsequentially fetched disk page </td><td>${random_page_cost}</td><td>The planner's assumption about the size of the disk cache</td><td>${effective_cache_size}</td></tr>\n  <tr><td> Number of simultaneous requests that can be handled efficiently by the disk subsystem </td><td>${effective_io_concurrency}</td><td>Forces synchronization of updates to disk </td><td>${fsync}</td></tr>\n  <tr><td> Starts the autovacuum subprocess </td><td>${autovacuum}</td><td>Number of tuple inserts, updates, or deletes prior to analyze as a fraction of reltuples</td><td>${autovacuum_analyze_scale_factor}</td></tr>\n  <tr><td> Minimum number of tuple inserts, updates, or deletes prior to analyze </td><td>${autovacuum_analyze_threshold}</td><td>Number of tuple updates or deletes prior to vacuum as a fraction of reltuples</td><td>${autovacuum_vacuum_scale_factor}</td></tr>\n  <tr><td> Minimum number of tuple updates or deletes prior to vacuum </td><td>${autovacuum_vacuum_threshold}</td><td>Vacuum cost amount available before napping, for autovacuum </td><td>${autovacuum_vacuum_cost_limit}</td></tr>\n  <tr><td> Vacuum cost delay in milliseconds, for autovacuum (seconds) </td><td>${autovacuum_vacuum_cost_delay}</td><td> The maximum number of simultaneously running autovacuum worker processes </td><td>${autovacuum_max_workers}</td></tr>\n  <tr><td> Time to sleep between autovacuum runs (seconds) </td><td>${autovacuum_naptime}</td><td>Age at which to autovacuum a table to prevent transaction ID wraparound </td><td>${autovacuum_freeze_max_age}</td></tr>\n  <tr><td> The maximum memory to be used by each autovacuum worker process (bytes)</td><td>${autovacuum_work_mem}</td><td>Multixact age at which to autovacuum a table to prevent multixact wraparound</td><td>${autovacuum_multixact_freeze_max_age}</td></tr>\n  <tr><td> Start a subprocess to capture stderr output and/or csvlogs into log files </td><td>${logging_collector}</td><td>Sets the minimum execution time above which statements will be logged (seconds) </td><td>${log_min_duration_statement}</td></tr>\n  <tr><td> Logs the duration of each completed SQL statement </td><td>${log_duration}</td><td>Logs long lock waits </td><td>${log_lock_waits}</td></tr>\n  <tr><td></td><td></td><td></td><td></td></tr>\n</table>\n\n"
     }
    }
   ]
  },
  {
   "title": "Node Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 98 },
   "collapsed": true,
   "panels": [
    {
     "title": "System Uptime",
     "type": "stat",
     "description": "The parameter shows how long a system has been “up” and running without a shut down or restart.",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 101 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "avg by (node_name) ((node_time_seconds{node_name=~\"$node_name\"} - node_boot_time_seconds{node_name=~\"$node_name\"}) or (time() - node_boot_time_seconds{node_name=~\"$node_name\"}))"
      }
     ]
    },
    {
     "title": "Load Average",
     "type": "stat",
     "description": "The system load is a measurement of the computational work the system is performing. Each running process either using or waiting for CPU resources adds 1 to the load.",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 101 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (node_name) (avg_over_time(node_load1{node_name=~\"$node_name\"}[$interval]) or avg_over_time(node_load1{node_name=~\"$node_name\"}[5m]))"
      }
     ]
    },
    {
     "title": "RAM",
     "type": "stat",
     "description": "RAM (Random Access Memory) is the hardware in a computing device where the operating system, application programs and data in current use are kept so they can be quickly reached by the device's processor.",
     "gridPos": { "h": 3, "w": 3, "x": 6, "y": 101 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (node_name) (node_memory_MemTotal_bytes{node_name=~\"$node_name\"})"
      }
     ]
    },
    {
     "title": "Memory Available",
     "type": "stat",
     "description": "Percent of Memory Available\nNote: on Modern Linux Kernels amount of Memory Available for application is not the same as Free+Cached+Buffers",
     "gridPos": { "h": 3, "w": 3, "x": 9, "y": 101 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (node_name) ((node_memory_MemAvailable_bytes{node_name=~\"$node_name\"} or (node_memory_MemFree_bytes{node_name=~\"$node_name\"} + node_memory_Buffers_bytes{node_name=~\"$node_name\"} + node_memory_Cached_bytes{node_name=~\"$node_name\"})) / node_memory_MemTotal_bytes{node_name=~\"$node_name\"} * 100)"
      }
     ]
    },
    {
     "title": "Virtual Memory",
     "type": "stat",
     "description": "RAM + SWAP",
     "gridPos": { "h": 3, "w": 3, "x": 12, "y": 101 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (node_name) (node_memory_MemTotal_bytes{node_name=~\"$node_name\"}+node_memory_SwapTotal_bytes{node_name=~\"$node_name\"})"
      }
     ]
    },
    {
     "title": "Disk Space",
     "type": "stat",
     "description": "Sum of disk space on all partitions. Note  it can be significantly over-reported in some installations",
     "gridPos": { "h": 3, "w": 3, "x": 15, "y": 101 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (node_name) (sum(avg(node_filesystem_size_bytes{node_name=~\"$node_name\",fstype=~\"(ext.|xfs|vfat|)\"}) without (mountpoint)) without (device,fstype))"
      }
     ]
    },
    {
     "title": "Min Space Available",
     "type": "stat",
     "description": "Lowest percent of the disk space available",
     "gridPos": { "h": 3, "w": 3, "x": 18, "y": 101 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "min(node_filesystem_free_bytes{node_name=~\"$node_name\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs|shm|overlay|squashfs\"}/node_filesystem_size_bytes{node_name=~\"$node_name\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs|shm|overlay|squashfs\"})*100"
      }
     ]
    },
    {
     "title": "Node",
     "type": "text",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 101 },
     "options": {
      "content": "<h5 style='color:#e68a00;font-weight:bold;text-align:center'><a href=\"/graph/d/node-instance-summary/node-summary?var-node_name=$node_name\" target=\"_blank\">$crop_host...</a></h5>"
     }
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "description": "The CPU time is measured in clock ticks or seconds. It is useful to measure CPU time as a percentage of the CPU's capacity, which is called the CPU usage.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "avg by (node_name,mode) (clamp_max(((avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{node_name=~\"$node_name\",mode!=\"idle\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{node_name=~\"$node_name\",mode!=\"idle\"}[5m]),1)) ))*100 or (avg_over_time(node_cpu_average{node_name=~\"$node_name\", mode!=\"total\", mode!=\"idle\"}[$interval]) or avg_over_time(node_cpu_average{node_name=~\"$node_name\", mode!=\"total\", mode!=\"idle\"}[5m]))),100))",
       "legendFormat": "{{ mode }}"
      }
     ]
    },
    {
     "title": "CPU Saturation and Max Core Usage",
     "type": "graph",
     "description": "When a system is running with maximum CPU utilization, the transmitting and receiving threads must all share the available CPU. This will cause data to be queued more frequently to cope with the lack of CPU. CPU Saturation may be measured as the length of a wait queue, or the time spent waiting on the queue.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 104 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "avg by (node_name) ((avg_over_time(node_procs_running{node_name=~\"$node_name\"}[$interval])-1) / scalar(count(node_cpu_seconds_total{mode=\"user\", node_name=~\"$node_name\"})) or (avg_over_time(node_procs_running{node_name=~\"$node_name\"}[5m])-1) / scalar(count(node_cpu_seconds_total{mode=\"user\", node_name=~\"$node_name\"})))",
       "legendFormat": "Normalized CPU Load"
      },
      {
       "calculatedInterval": "2s",
       "expr": "clamp_max(max by () (sum  by (cpu) ( (clamp_max(rate(node_cpu_seconds_total{node_name=~\"$node_name\",mode!=\"idle\",mode!=\"iowait\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{node_name=~\"$node_name\",mode!=\"idle\",mode!=\"iowait\"}[5m]),1)) )),1)",
       "legendFormat": "Max CPU Core Utilization"
      }
     ]
    },
    {
     "title": "Disk I/O and Swap Activity",
     "type": "graph",
     "description": "Disk I/O includes read or write or input/output operations involving a physical disk. It is the speed with which the data transfer takes place between the hard disk drive and RAM.\n\nSwap Activity is memory management that involves swapping sections of memory to and from physical storage.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 112 },
     "yaxes": [
      { "format": "Bps", "label": "Page Out (-) / Page In (+)" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "avg by (node_name) (rate(node_vmstat_pgpgin{node_name=\"$node_name\"}[$interval]) * 1024 or irate(node_vmstat_pgpgin{node_name=\"$node_name\"}[5m]) * 1024)",
       "legendFormat": "Disk Reads (Page In)"
      },
      {
       "calculatedInterval": "2s",
       "expr": "avg by (node_name) ((rate(node_vmstat_pgpgout{node_name=\"$node_name\"}[$interval]) * 1024 or irate(node_vmstat_pgpgout{node_name=\"$node_name\"}[5m]) * 1024))",
       "legendFormat": "Disk Writes (Page Out)"
      },
      {
       "expr": "avg by (node_name) ((rate(node_vmstat_pgpgin{node_name=\"$node_name\"}[$interval]) * 1024 or irate(node_vmstat_pgpgin{node_name=\"$node_name\"}[5m]) * 1024 ) + (rate(node_vmstat_pgpgout{node_name=\"$node_name\"}[$interval]) * 1024 or irate(node_vmstat_pgpgout{node_name=\"$node_name\"}[5m]) * 1024))",
       "legendFormat": "Total"
      },
      {
       "expr": "avg by (node_name) (rate(node_vmstat_pswpin{node_name=\"$node_name\"}[$interval]) * 4096 or irate(node_vmstat_pswpin{node_name=\"$node_name\"}[5m]) * 4096)",
       "legendFormat": "Swap In (Reads)"
      },
      {
       "expr": "avg by (node_name) (rate(node_vmstat_pswpout{node_name=\"$node_name\"}[$interval]) * 4096 or irate(node_vmstat_pswpout{node_name=\"$node_name\"}[5m]) * 4096)",
       "legendFormat": "Swap Out (Writes)"
      }
     ]
    },
    {
     "title": "Network Traffic",
     "type": "graph",
     "description": "Network traffic refers to the amount of data moving across a network at a given point in time.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 112 },
     "yaxes": [
      { "format": "Bps", "label": "Outbound (-) / Inbound (+)" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "avg by (node_name) (sum(rate(node_network_receive_bytes_total{node_name=\"$node_name\", device!=\"lo\"}[$interval])) or sum(irate(node_network_receive_bytes_total{node_name=\"$node_name\", device!=\"lo\"}[5m])) or sum(max_over_time(rdsosmetrics_network_rx{node_name=\"$node_name\"}[$interval])) or sum(max_over_time(rdsosmetrics_network_rx{node_name=\"$node_name\"}[5m])))",
       "legendFormat": "Inbound"
      },
      {
       "calculatedInterval": "2s",
       "expr": "avg by (node_name) (sum(rate(node_network_transmit_bytes_total{node_name=\"$node_name\", device!=\"lo\"}[$interval])) or sum(irate(node_network_transmit_bytes_total{node_name=\"$node_name\", device!=\"lo\"}[5m])) or\nsum(max_over_time(rdsosmetrics_network_tx{node_name=\"$node_name\"}[$interval])) or sum(max_over_time(rdsosmetrics_network_tx{node_name=\"$node_name\"}[5m])))",
       "legendFormat": "Outbound"
      }
     ]
    }
   ]
  }
 ]
}