{
 "title": "MongoDB Instances Compare",
 "tags": [
  "MongoDB_Compare",
  "Percona"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "region",
    "label": "Region",
    "query": {
     "query": "label_values(mongodb_up{node_name=~\"$node_name\"}, region)"
    }
   },
   {
    "name": "node_name",
    "label": "Node Name",
    "query": {
     "query": "label_values(mongodb_up{service_name=~\"$service_name\"}, node_name)"
    }
   },
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values(mongodb_up{node_name=~\"$node_name\"}, environment)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(mongodb_up{node_name=~\"$node_name\"}, cluster)"
    }
   },
   {
    "name": "service_name",
    "label": "Service Name",
    "query": {
     "query": "label_values(mongodb_up, service_name)"
    }
   },
   {
    "name": "node_id",
    "label": "Node_ID",
    "query": {
     "query": "label_values(mongodb_up{node_name=\"$node_name\"}, node_id)"
    }
   },
   {
    "name": "agent_id",
    "label": "Agent_ID",
    "query": {
     "query": "label_values(mongodb_up{node_name=\"$node_name\"}, instance)"
    }
   },
   {
    "name": "service_id",
    "label": "Service_ID",
    "query": {
     "query": "label_values(mongodb_up{service_name=~\"$service_name\"}, service_id)"
    }
   },
   {
    "name": "az",
    "label": "Az",
    "query": {
     "query": "label_values(mongodb_up{node_name=\"$node_name\"}, az)"
    }
   },
   {
    "name": "node_type",
    "label": "Node_type",
    "query": {
     "query": "label_values(mongodb_up{node_name=\"$node_name\"}, node_type)"
    }
   },
   {
    "name": "node_model",
    "label": "Node_model",
    "query": {
     "query": "label_values(mongodb_up{node_name=\"$node_name\"}, node_model)"
    }
   },
   {
    "name": "replication_set",
    "label": "Replication Set",
    "query": {
     "query": "label_values(mongodb_up{service_name=~\"$service_name\"}, replication_set)"
    }
   },
   {
    "name": "database",
    "label": "Database",
    "query": {
     "query": "label_values(pg_stat_database_tup_fetched{service_name=~\"$service_name\",datname!~\"template.*|postgres\"},datname)"
    }
   },
   {
    "name": "service_type",
    "label": "Type",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, service_type)"
    }
   },
   {
    "name": "username",
    "label": "Username",
    "query": {
     "query": "label_values(mysql_info_schema_user_statistics_connected_time_seconds_total{service_name=\"$service_name\"},user)"
    }
   },
   {
    "name": "schema",
    "label": "Schema",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, schema)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$service_name - Service Info",
   "type": "table-old",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "repeat": "service_name",
   "targets": [
    {
     "expr": "mongodb_version_info{service_name=~\"$service_name\"}"
    }
   ]
  },
  {
   "title": "$service_name - MongoDB Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 5 },
   "repeat": "service_name",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "avg by (service_name) (mongodb_instance_uptime_seconds{service_name=~\"$service_name\"})"
    }
   ]
  },
  {
   "title": "$service_name - Current QPS",
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 7 },
   "repeat": "service_name",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (service_name) (rate(mongodb_op_counters_total{service_name=~\"$service_name\",type!=\"command\"}[$interval]) or irate(mongodb_op_counters_total{service_name=~\"$service_name\",type!=\"command\"}[5m]))"
    }
   ]
  },
  {
   "title": "$service_name - DB Connections",
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 9 },
   "repeat": "service_name",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (service_name) (max_over_time(mongodb_connections{service_name=~\"$service_name\",state=\"current\"}[$interval]) or max_over_time(mongodb_connections{service_name=~\"$service_name\",state=\"current\"}[5m]))"
    }
   ]
  },
  {
   "title": "$service_name - Latency",
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 11 },
   "repeat": "service_name",
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "avg by (service_name) (rate(mongodb_mongod_op_latencies_latency_total{service_name=~\"$service_name\",type=\"command\"}[$interval]) / (rate(mongodb_mongod_op_latencies_ops_total{service_name=~\"$service_name\",type=\"command\"}[$interval]) > 0) or irate(mongodb_mongod_op_latencies_latency_total{service_name=~\"$service_name\",type=\"command\"}[5m]) / (irate(mongodb_mongod_op_latencies_ops_total{service_name=~\"$service_name\",type=\"command\"}[5m]) > 0))"
    }
   ]
  },
  {
   "title": "$service_name - Opened Cursors",
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 13 },
   "repeat": "service_name",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "sum(mongodb_mongod_metrics_cursor_open{service_name=~\"$service_name\"} or mongodb_mongod_cursors{service_name=~\"$service_name\"} or mongodb_mongos_metrics_cursor_open{service_name=~\"$service_name\"} or mongodb_mongos_cursors{service_name=~\"$service_name\"})"
    }
   ]
  },
  {
   "title": "$service_name - Replica Set",
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 15 },
   "repeat": "service_name",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "mongodb_mongod_replset_my_state{service_name=~\"$service_name\"}",
     "legendFormat": "{{set}}"
    }
   ]
  },
  {
   "title": "$service_name - ReplSet State",
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 17 },
   "repeat": "service_name",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_mongod_replset_my_state{service_name=~\"$service_name\"}"
    }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "$service_name - Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "repeat": "service_name",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (service_name,state) (max_over_time(mongodb_mongod_connections{service_name=~\"$service_name\", state=~\"current|available\"}[$interval]) or max_over_time(mongodb_mongod_connections{service_name=~\"$service_name\", state=~\"current|available\"}[5m]) or max_over_time(mongodb_mongos_connections{service_name=~\"$service_name\", state=~\"current|available\"}[$interval]) or max_over_time(mongodb_mongos_connections{service_name=~\"$service_name\", state=~\"current|available\"}[5m]) or \nmax_over_time(mongodb_connections{service_name=~\"$service_name\", state=~\"current|available\"}[$interval]) or \nmax_over_time(mongodb_connections{service_name=~\"$service_name\", state=~\"current|available\"}[5m]))",
     "legendFormat": "{{state}}"
    }
   ]
  },
  { "title": "Cursors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "$service_name - Cursors ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "repeat": "service_name",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (service_name,state) (mongodb_mongod_metrics_cursor_open{service_name=~\"$service_name\"} or \nmongodb_mongod_cursors{service_name=~\"$service_name\"} or \nmongodb_mongos_metrics_cursor_open{service_name=~\"$service_name\"} or \nmongodb_mongos_cursors{service_name=~\"$service_name\"})",
     "legendFormat": "{{state}}"
    }
   ]
  },
  { "title": "Query Efficiency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "$service_name - Latency",
   "type": "graph",
   "description": "Average latency of operations (classified by read, write, or (other) command)",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
   "repeat": "service_name",
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (service_name,type) (rate(mongodb_mongod_op_latencies_latency_total{service_name=~\"$service_name\"}[$interval]) / (rate(mongodb_mongod_op_latencies_ops_total{service_name=~\"$service_name\"}[$interval]) > 0) or\nirate(mongodb_mongod_op_latencies_latency_total{service_name=~\"$service_name\"}[5m]) / \n(irate(mongodb_mongod_op_latencies_ops_total{service_name=~\"$service_name\"}[5m]) > 0))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "$service_name - Scan Ratios",
   "type": "graph",
   "description": "Ratio of index entries scanned or whole docs scanned / number of documents returned",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 46 },
   "repeat": "service_name",
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (service_name) (rate(mongodb_mongod_metrics_query_executor_total{service_name=~\"$service_name\", state=\"scanned\"}[$interval]) / ignoring(state) rate(mongodb_mongod_metrics_document_total{service_name=~\"$service_name\", state=\"returned\"}[$interval]) or (irate(mongodb_mongod_metrics_query_executor_total{service_name=~\"$service_name\", state=\"scanned\"}[5m]) / ignoring(state) irate(mongodb_mongod_metrics_document_total{service_name=~\"$service_name\", state=\"returned\"}[5m])))",
     "legendFormat": "Index"
    },
    {
     "expr": "avg by (service_name) (rate(mongodb_mongod_metrics_document_total{service_name=~\"$service_name\", state=\"returned\"}[$interval]) / ignoring(state)rate(mongodb_mongod_metrics_query_executor_total{service_name=~\"$service_name\", state=\"scanned_objects\"}[$interval]) or\nirate(mongodb_mongod_metrics_document_total{service_name=~\"$service_name\", state=\"returned\"}[5m]) / ignoring(state)irate(mongodb_mongod_metrics_query_executor_total{service_name=~\"$service_name\", state=\"scanned_objects\"}[5m]))",
     "legendFormat": "Document"
    }
   ]
  },
  {
   "title": "$service_name - Index Filtering Effectiveness",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 54 },
   "repeat": "service_name",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum by (service_name) (mongodb_mongod_metrics_query_executor_total{service_name=~\"$service_name\", state=~\"scanned_objects\"}) / ignoring(state)sum by (service_name) (mongodb_mongod_metrics_query_executor_total{service_name=~\"$service_name\", state=~\"scanned_objects|scanned\"})",
     "legendFormat": "Index"
    }
   ]
  },
  { "title": "Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "$service_name - Requests",
   "type": "graph",
   "description": "Ops/sec (classified by (legacy) wire protocol request type)",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 63 },
   "repeat": "service_name",
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (service_name,type) (rate(mongodb_mongod_op_counters_total{service_name=~\"$service_name\"}[$interval]) or \nirate(mongodb_mongod_op_counters_total{service_name=~\"$service_name\"}[5m]) or \nrate(mongodb_mongos_op_counters_total{service_name=~\"$service_name\"}[$interval]) or \nirate(mongodb_mongos_op_counters_total{service_name=~\"$service_name\"}[5m]) or \nrate(mongodb_op_counters_total{service_name=~\"$service_name\"}[$interval]) or \nirate(mongodb_op_counters_total{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "$service_name - Document Operations",
   "type": "graph",
   "description": "Documents inserted/updated/deleted or returned per sec",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 71 },
   "repeat": "service_name",
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (service_name,state) (rate(mongodb_mongod_metrics_document_total{service_name=~\"$service_name\"}[$interval]) or \nirate(mongodb_mongod_metrics_document_total{service_name=~\"$service_name\"}[5m]))\n",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "$service_name - Queued Operations",
   "type": "graph",
   "description": "The number of operations that are currently queued and waiting for a lock",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 79 },
   "repeat": "service_name",
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (service_name,type) (max_over_time(mongodb_mongod_global_lock_current_queue{service_name=~\"$service_name\"}[$interval]) or max_over_time(mongodb_mongod_global_lock_current_queue{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 } },
  {
   "title": "$service_name - Used Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 88 },
   "repeat": "service_name",
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "avg by (service_name,type) (max_over_time(mongodb_memory{service_name=~\"$service_name\"}[$interval]) or\nmax_over_time(mongodb_memory{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}