version: '3.7'

services:
  ingress:
    image: traefik
    restart: always
    logging:
      driver: "json-file"
      options: 
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
        max-size: "100m"
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost:8080/ping"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    environment:
      LEGO_CA_CERTIFICATES: "/root_ca.crt"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${APP_DATA}/base/ingress/:/etc/traefik/"
      - "${APP_DATA}/base/ca/certs/root_ca.crt:/root_ca.crt:ro"
    ports:
      - "80:80" # web Entrypoint
      - "443:443" # websecure Entrypoint
      - "8080:8080" # Traefik Dashboard
      - "6379:6379" # Redis TCP Entrypoint
      - "3306:3306" # MySQL TCP Entrypoint
      - "5432:5432" # PostgreSQL TCP Entrypoint
    depends_on:
      - labtastic-ca
    networks:
      - labtastic
    labels:
      - "com.centurylinklabs.watchtower.enable=${AUTO_UPDATE}"
      - "prometheus-job=traefik"

  labtastic-ca:
    image: smallstep/step-ca
    restart: always
    logging:
      driver: "json-file"
      options: 
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
        max-size: "100m"
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost:9000/health"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    environment:
      DOCKER_STEPCA_INIT_NAME: Labtastic
      DOCKER_STEPCA_INIT_DNS_NAMES: localhost,labtastic-ca,ca.${DOMAIN}
      DOCKER_STEPCA_INIT_SSH: "yes"
      DOCKER_STEPCA_INIT_PASSWORD: ${BASE_CA_INIT_PASSWORD}
    volumes:
      - "$APP_DATA/base/ca/:/home/step/"
    networks:
      - labtastic
    labels:
      - "com.centurylinklabs.watchtower.enable=${AUTO_UPDATE}"
      - "prometheus-job=labtastic-ca"
      - "labtastic.dns.domain=${DOMAIN}"
      - "labtastic.dns.recordName=ca"
      - "traefik.enable=true"
      - "traefik.tcp.routers.base-ca.rule=HostSNI(`ca.${DOMAIN}`)"
      - "traefik.tcp.routers.base-ca.entrypoints=web, websecure"
      - "traefik.tcp.routers.base-ca.tls=true"
      - "traefik.tcp.routers.base-ca.tls.passthrough=true"
      - "traefik.tcp.services.base-ca.loadbalancer.server.port=9000"
  
  watchtower:
    image: containrrr/watchtower
    restart: always
    logging:
      driver: "json-file"
      options: 
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
        max-size: "100m"
    environment:
      WATCHTOWER_LABEL_ENABLE: "true"
      WATCHTOWER_HTTP_API_TOKEN: "${BASE_WATCHTOWER_API_TOKEN:-labtastic}"
      WATCHTOWER_HTTP_API_METRICS: "${BASE_WATCHTOWER_API_METRICS:-true}"
      WATCHTOWER_TIMEOUT: "${BASE_WATCHTOWER_TIMEOUT:-60s}"
      WATCHTOWER_CLEANUP: "${BASE_WATCHTOWER_CLEANUP:-true}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "com.centurylinklabs.watchtower.enable=${AUTO_UPDATE}"
      - "prometheus-job=watchtower"
    networks:
      - labtastic
  
  dns:
    image: technitium/dns-server
    restart: always
    logging:
      driver: "json-file"
      options: 
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
        max-size: "100m"
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost:5380/api/"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - labtastic
    environment:
      DNS_SERVER_DOMAIN: "dns.${DOMAIN}"
      DNS_SERVER_ADMIN_PASSWORD: "${BASE_DNS_ADMIN_PASSWORD}"
      DNS_SERVER_PREFER_IPV6: "${BASE_DNS_SERVER_PREFER_IPV6}"
      DNS_SERVER_OPTIONAL_PROTOCOL_DNS_OVER_HTTP: "${BASE_DNS_SERVER_OPTIONAL_PROTOCOL_DNS_OVER_HTTP}"
      DNS_SERVER_RECURSION: "${BASE_DNS_SERVER_RECURSION}"
      DNS_SERVER_ENABLE_BLOCKING: "${BASE_DNS_SERVER_ENABLE_BLOCKING}"
      DNS_SERVER_ALLOW_TXT_BLOCKING_REPORT: "${BASE_DNS_SERVER_ALLOW_TXT_BLOCKING_REPORT}"
      DNS_SERVER_FORWARDERS: "${BASE_DNS_SERVER_FORWARDERS}"
      DNS_SERVER_FORWARDER_PROTOCOL: "${BASE_DNS_SERVER_FORWARDER_PROTOCOL}"
      DNS_SERVER_LOG_USING_LOCAL_TIME: "${BASE_DNS_SERVER_LOG_USING_LOCAL_TIME}"
    labels:
      - "com.centurylinklabs.watchtower.enable=${AUTO_UPDATE}"
      - "prometheus-job=dns"
      - "labtastic.dns.domain=${DOMAIN}"
      - "labtastic.dns.recordName=dns"
      - "traefik.enable=true"
      - "traefik.http.routers.base-dns.rule=Host(`dns.${DOMAIN}`)"
      - "traefik.http.routers.base-dns.entrypoints=web, websecure"
      - "traefik.http.routers.base-dns.tls=true"
      - "traefik.http.routers.base-dns.tls.certresolver=labtastic"
      - "traefik.http.services.base-dns.loadbalancer.server.port=5380"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - "$APP_DATA/base/dns/:/etc/dns/config/"

networks:
  labtastic:
    external: true
